name: mealify_consumer
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  velocity_x: ^3.6.0

  
  get: ^4.6.5

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  google_sign_in: ^5.4.4
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  google_fonts: ^6.2.1
  flutter_otp_text_field: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/category_model.json